import Head from 'next/head';
import styles from '../styles/Home.module.css';
import CardList from '../components/organisms/cardList/CardList';
import { useUser } from '@auth0/nextjs-auth0';
import Menu from '../components/molecules/menu/Menu';
import { useEffect, useState } from 'react';

export default function Home() {
  const { user } = useUser();
  const [basePokemonData, setBasePokemonData] = useState([]);

  useEffect(() => {
    const fetchPokemonData = (pokemon: any) => {
      fetch(`https://pokeapi.co/api/v2/pokemon-species/${pokemon.name}`)
        .then((response) => {
          return response.json();
        })
        .then((pokemon) => {
          setBasePokemonData((basePokemonData): any => [
            ...basePokemonData,
            {
              name: `${pokemon.names[4].name}`,
              numero: `${pokemon.id}`,
            },
          ]);
        });
    };

    fetch('https://pokeapi.co/api/v2/pokemon?limit=151')
      .then((response) => {
        return response.json();
      })
      .then((allPokemon) => {
        allPokemon.results.forEach((pokemon: any) => {
          fetchPokemonData(pokemon);
        });
      });
  }, []);

  return (
    <>
      <Menu user={user} />
      <div className={styles.container}>
        <Head>
          <title>Pokemon Collection</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Pokémon Collection</h1>
          {user && <CardList basePokemonData={basePokemonData} />}
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
